databaseChangeLog:
  - changeSet:
      id: 4
      author: Diana-Kieru
      changes:
        - createTable:
            tableName: product
            columns:
              - column:
                  name: id
                  type: bigint
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: varchar(255)
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: short_description
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: long_description
                  type: varchar(255)
              - column:
                  name: price
                  type: double
                  constraints:
                    nullable: false